site_name: 中国常见法定证件文本结构特征与信息化 OCR 识别版式规范指南
site_url: https://gnzmjs.readthedocs.io/zh-cn/latest/
theme:
  name: material
  custom_dir: overrides

nav:
  - 首页: index.md
  - 1. 营业执照: business_license.md
  - 2. 房产证不动产权证书: property_certificate.md
  - 3. 毕业证书: bachelor.md
  - 4. 离婚证 (Divorce Certificate): divorce_certificate.md
  - 5. 机动车登记证书 (Vehicle Registration): vehicle_registration.md
  - 附录 (Appendix):
      - 常见证件防伪特征概述: appendix/security_features.md
      - 常用术语中英文对照表: appendix/glossary.md
